version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t sklearn-base:0.21.2-cpu-py3 -f docker/0.21.2/base/Dockerfile.cpu .
    - pip install wheel setuptools
    - python setup.py bdist_wheel
    - docker build -t preprod-sklearn:0.21.2-cpu-py3 -f docker/0.21.2/final/Dockerfile.cpu .
    - docker build -t preprod-sklearn:extension-0.1.0-cpu-py3 -f docker/0.21.2/extension/Dockerfile.cpu .
    - docker tag preprod-sklearn:extension-0.1.0-cpu-py3 515193369038.dkr.ecr.us-west-2.amazonaws.com/sagemaker-sklearn-automl:0.1.0-cpu-py3
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 515193369038.dkr.ecr.us-west-2.amazonaws.com/sagemaker-sklearn-automl:0.1.0-cpu-py3